version: '3.8'

services:
  web:
    build: .
    container_name: fastapi_app
    command: uvicorn app.main:app --host 0.0.0.0 --port 9000 --reload
    ports:
      - "9000:9000"
    volumes:
      - .:/app
      - ./db.sqlite3:/app/db.sqlite3
